### PR TITLE
Adding set/delete methods for symmetry

### LINKED ISSUE #3: Consider adding a `set` method for the sake of symmetry?
Hey Matthieu,

I'm using Simplex quite a lot for testing my service providers, and I'm even (dangerously) using it in a project right now.

There is something weird however. Because Simplex is Pimple + ContainerInterop, it has a `get` and `has` method, but no `set` method.

When writing code, this leads to weird looking stuff like this: https://github.com/thecodingmachine/doctrine-annotations-universal-module/blob/1.0/tests/DoctrineAnnotationsServiceProviderTest.php#L26-L32

If I wrote a simple pull-request to add a `set` method that is simply an alias to `offsetSet`, would you accept it, or do you consider it to be out of scope of Simplex?

### PR DESCRIPTION
**Pull request by moufmouf**
Closes #3 .
Note I also added a `delete`  method (also for symmetry with `unset`), even if this is really less used than `set`.

### CODE REVIEW

**Comment by moufmouf** [comment]
(just realized I forgot the unit tests... you can wait a bit before merging!)

**Comment by moufmouf** [comment]
Unit tests added. Ready to merge.

**Comment by mnapoli** [comment]
Thanks! However sorry to be picky but I don't think adding `delete()` is worth it ;) I think it has been added in Pimple because of ArrayAccess but it's not a widespread feature, and if it wasn't for `ArrayAccess` it wouldn't exist. I can merge and update the code if you prefer, just let me know.

**Comment by moufmouf** [comment]
No problem, that's done. I just removed `delete`. I completely understand and can definitely live without a `delete` method. It's never used anyway.

**Comment by mnapoli** [comment]
Nice thanks!

**Pull request merged**
