### PR TITLE
Register all service providers in constructor. Allow to register all …

### PR DESCRIPTION
**Pull request by pmall**
…factories before the extensions.

### CODE REVIEW

**Comment by pmall** [comment]
After some through it may be better to let the register method public. This way you can pass the container to something which will register a bunch of service providers.

**Comment by moufmouf** [comment]
I'm :+1: for the PR as it is.

I'm not completely sure switching back `register` to public can be useful in practice. First, we are going to have issue #7 back.

And I mean, it looks like we are going a bit meta. A service provider is already something that registers an array of services in a container. Do we need something that registers an array of service providers? (i.e. do we need something that registers an array of things that registers an array of services? :) )

On the other end, I was thinking that we may rename `register` to `registerContainerInteropServiceProvider` and revert the `register` method to it's initial purpose (in Pimple 3), that is: registering a "Pimple service provider".

That way, Simplex could load both service providers from container-interop and from Pimple.

@mnapoli any thoughts?

**Comment by pmall** [comment]
@moufmouf Agree. I'm thinking about features like laravel auto discovery which retrieve a list of service providers from the installed packages. But I was wrong yesterday, we can totally have something to generate this list then instantiate the container. Private register method is ok.

**Comment by moufmouf** [comment]
Ping @mnapoli .

Any chance we can merge this? Seems ok to me and it fixes an important implementation issue.

**Comment by mnapoli** [comment]
Sorry merging!

**Pull request merged**
